insert into chenht_Students values ('S01', '王建平', 'WJP@zjut.edu.cn', 23.1, '男')
insert into chenht_Students values ('S02', '刘华', 'LH@zjut.edu.cn', 34.6, '女')
insert into chenht_Students values ('S03', '范林军', 'FLJ@zjut.edu.cn', 16.6, '女')
insert into chenht_Students values ('S04', '李伟', 'LW@zjut.edu.cn', 15.8, '男')
insert into chenht_Students values ('S26', '黄河', 'Huanghe@zjut.edu.cn', 13.4, '男')
insert into chenht_Students values ('S52', '长江', 'Changjiang@zjut.edu.cn', 12.4, '男')

insert into chenht_Teachers values ('T01', '刘涛', 'LT@zjut.edu.cn', 4300)
insert into chenht_Teachers values ('T02', '吴碧燕', 'WBY@zjut.edu.cn', 2500)
insert into chenht_Teachers values ('T03', '张莹', 'ZY@zjut.edu.cn', 3000)
insert into chenht_Teachers values ('T04', '张宁亚', 'ZNY@zjut.edu.cn', 5500)
insert into chenht_Teachers values ('T05', '叶烨', 'Yeye@zjut.edu.cn', 3800)
insert into chenht_Teachers values ('T06', '杨兰', 'YL@zjut.edu.cn', 3500)
insert into chenht_Teachers values ('T07', '程媛媛', 'ChengYY@zjut.edu.cn', 5000)

insert into chenht_Courses values ('C01', 'C++', 4)
insert into chenht_Courses values ('C02', 'UML', 3)
insert into chenht_Courses values ('C03', 'Java', 3)
insert into chenht_Courses values ('C04', '算法分析与设计', 2)
insert into chenht_Courses values ('C05', '数据库原理及其应用', 2)
insert into chenht_Courses values ('C06', '数据结构与算法分析', 2)
insert into chenht_Courses values ('C07', '英语', 4)

insert into chenht_Reports values('S01', 'T01', 'C01', 83)
insert into chenht_Reports values('S01', 'T03', 'C03', 83)
insert into chenht_Reports values('S02', 'T01', 'C01', 75)
insert into chenht_Reports values('S02', 'T02', 'C02', 59)
insert into chenht_Reports values('S02', 'T03', 'C03', NULL)
insert into chenht_Reports values('S02', 'T04', 'C04', NULL)
insert into chenht_Reports values('S02', 'T05', 'C05', 77)
insert into chenht_Reports values('S02', 'T06', 'C06', 86)
insert into chenht_Reports values('S02', 'T07', 'C07', 80)
insert into chenht_Reports values('S03', 'T02', 'C02', 88)
insert into chenht_Reports values('S03', 'T04', 'C04', 76)
insert into chenht_Reports values('S04', 'T05', 'C05', 90)
insert into chenht_Reports values('S04', 'T06', 'C06', 89)
insert into chenht_Reports values('S26', 'T04', 'C04', 72)
insert into chenht_Reports values('S26', 'T05', 'C05', 95)
insert into chenht_Reports values('S26', 'T07', 'C07', 55)
insert into chenht_Reports values('S52', 'T01', 'C01', 61)
insert into chenht_Reports values('S52', 'T05', 'C05', 90)
insert into chenht_Reports values('S52', 'T07', 'C07', NULL)